namespace SheetXExample
{
	/***
	 * This script is automatically generated by SheetX.
	 ***/
	
	using System;
	using System.Collections.Generic;
	using TMPro;
	using UnityEngine;
	using UnityEngine.UI;
	using System.Text.RegularExpressions;
	#if UNITY_EDITOR
	using UnityEditor;
	#endif
	
	[DisallowMultipleComponent]
	public class LocalizationDialogueText : MonoBehaviour
	{
	    public enum CaseType
	    {
	        None,
	        LowerCase,
	        UpperCase,
	        SentenceCase,
	        CapitalizeEachWord,
	    }
	
	    [SerializeField] private TextMeshProUGUI m_TxtPro;
	    [SerializeField] private TextMeshPro m_TxtPro3D;
	    [SerializeField] private Text m_Txt;
	    [SerializeField] private string m_LocalizedIDString;
	    [SerializeField] private CaseType m_CaseType;
		[SerializeField] private string[] m_Args;
		[SerializeField] private List<string> m_IgnoredLangs = new List<string>(); //Used for TMPPRo
	    [SerializeField, HideInInspector] private LocalizationDialogue.ID m_LocalizedEnumId = LocalizationDialogue.ID.NONE; //Used to search for the usage of an ID within the project
	    [NonSerialized] private int m_LocalizedID = -1;
		
		private int m_LanguageIndex = -1;
		public string LocalizedIDString => m_LocalizedIDString;
	    public LocalizationDialogue.ID LocalizedEnumId => m_LocalizedEnumId;
	
		private void Awake()
	    {
			Init();
	    }
	
	    private void OnEnable()
	    {
	        if (LocalizationDialogue.CurLangIndex > -1)
	            Refresh();
			
			LocalizationDialogue.OnLanguageChanged += OnLanguageChanged;
	    }
		
	    private void OnDisable()
	    {
			LocalizationDialogue.OnLanguageChanged -= OnLanguageChanged;
		}
		
	    public void Set(int pId, params string[] pArgs)
	    {
	        if (m_LocalizedID != pId)
	        {
	            m_LocalizedID = pId;
	            m_LocalizedEnumId = (LocalizationDialogue.ID)pId;
	            m_LocalizedIDString = LocalizationDialogue.idString[m_LocalizedID];
	        }
			m_Args = pArgs;
			Refresh();
	    }
	
	    public void Set(string pId, string[] pArgs)
	    {
	        if (m_LocalizedIDString != pId)
	        {
	            m_LocalizedIDString = pId;
	            m_LocalizedID = -1;
	            m_LocalizedEnumId = LocalizationDialogue.ID.NONE;
	        }
			m_Args = pArgs;
			Refresh();
	    }
	
	    public void SetArgs(params string[] pArgs)
		{
		    m_Args = pArgs;
		    Refresh();
		}
	
	    private void Init()
	    {
	        if (m_TxtPro == null && m_Txt == null && m_TxtPro3D == null)
	        {
	            m_TxtPro = gameObject.GetComponent<TextMeshProUGUI>();
	            m_Txt = gameObject.GetComponent<Text>();
	            m_TxtPro3D = gameObject.GetComponent<TextMeshPro>();
	        }
	    }
	
	    public void Refresh()
	    {
			int CurLangIndex = LocalizationDialogue.CurLangIndex;
	        if (Application.isPlaying && m_LanguageIndex == CurLangIndex)
				return;
			if (m_IgnoredLangs.Count > 0 && m_IgnoredLangs.Contains(LocalizationDialogue.CurrentLanguage))
				return;
	        string text = "";
	        if (m_LocalizedID >= 0)
	            text = LocalizationDialogue.Get(m_LocalizedID).ToString();
	        else if (!string.IsNullOrEmpty(m_LocalizedIDString))
	            text = LocalizationDialogue.Get(m_LocalizedIDString, ref m_LocalizedID).ToString();
	        switch (m_CaseType)
	        {
	            case CaseType.LowerCase:
	                text = text.ToLower();
	                break;
	            case CaseType.SentenceCase:
	                text = ToSentenceCase(text);
	                break;
	            case CaseType.CapitalizeEachWord:
	                text = ToCapitalizeEachWord(text);
	                break;
	            case CaseType.UpperCase:
	                text = text.ToUpper();
	                break;
	        }
	        if (m_Args != null && m_Args.Length > 0)
	            text = string.Format(text, m_Args);
	        if (m_Txt != null && !string.IsNullOrEmpty(text))
	            m_Txt.text = text;
	        if (m_TxtPro != null && !string.IsNullOrEmpty(text))
	            m_TxtPro.text = text;
	        if (m_TxtPro3D != null && !string.IsNullOrEmpty(text))
	            m_TxtPro3D.text = text;
				
			m_LanguageIndex = CurLangIndex;
	    }
		
		private void OnLanguageChanged()
		{
			Refresh();
		}
	
	    private string ToCapitalizeEachWord(string pString)
	    {
	        return Regex.Replace(pString, @"(^\w)|(\s\w)", m => m.Value.ToUpper());
	    }
	
	    private string ToSentenceCase(string pString)
	    {
	        var lowerCase = pString.ToLower();
	        var r = new Regex(@"(^[a-z])|\.\s+(.)", RegexOptions.ExplicitCapture);
	        var result = r.Replace(lowerCase, s => s.Value.ToUpper());
	        return result;
	    }
	
	#if UNITY_EDITOR
	    private void OnValidate()
	    {
	        if (Application.isPlaying)
	            return;
	
	        Init();
	
	        if (string.IsNullOrEmpty(m_LocalizedIDString))
				return;
			
			int localizedID = -1;
	        LocalizationDialogue.InitInEditor();
			LocalizationDialogue.Get(m_LocalizedIDString, ref localizedID);
			if (localizedID == -1)
			{
				string path = name;
				var parent = transform.parent;
				while (parent != null)
				{
					path = $"{parent.name}.{path}";
					parent = parent.parent;
				}
				Debug.LogError($"{path}: not found {m_LocalizedIDString} in {nameof(LocalizationDialogue)}");
			}
	    }
	
	    [CustomEditor(typeof(LocalizationDialogueText))]
	    public class LocalizationDialogueTextEditor : Editor
	    {
	        private LocalizationDialogueText m_Target;
	        private string m_Search;
	        private bool m_ShowText;
	        private int m_MaxResults;
			private int m_IgnoredLangIdx;
	
	        private void OnEnable()
	        {
	            LocalizationDialogue.InitInEditor();
	            m_MaxResults = 20;
	            m_Target = target as LocalizationDialogueText;
	        }
	
	        public override void OnInspectorGUI()
	        {
	            base.OnInspectorGUI();
	
	            EditorGUILayout.LabelField("Editor", GUI.skin.horizontalSlider);
	
	            GUILayout.BeginHorizontal();
	            EditorGUILayout.LabelField("Search Key", GUILayout.Width(100));
	            m_Search = EditorGUILayout.TextField(m_Search, EditorStyles.textField);
	            EditorGUILayout.LabelField("Show Text", GUILayout.Width(80));
	            m_ShowText = EditorGUILayout.Toggle(m_ShowText);
	            GUILayout.EndHorizontal();
	
	            if (GUILayout.Button("Refresh"))
	                m_Target.Refresh();
					
				if (LocalizationDialogue.CurrentLanguage != LocalizationDialogue.DefaultLanguage && GUILayout.Button("Reset Default Language"))
	            {
					LocalizationDialogue.CurrentLanguage = LocalizationDialogue.DefaultLanguage;
					m_Target.Refresh();
				}
				
				if (GUILayout.Button("Add Ignored Lang"))
					m_Target.m_IgnoredLangs.Add("");
				if (m_Target.m_IgnoredLangs.Count > 0)
				{
					for (int i = 0; i < m_Target.m_IgnoredLangs.Count; i++)
					{
						GUILayout.BeginHorizontal();
						m_Target.m_IgnoredLangs[i] = EditorGUILayout.TextField(m_Target.m_IgnoredLangs[i], EditorStyles.textField);
						if (GUILayout.Button("<"))
						{
							m_IgnoredLangIdx--;
							m_IgnoredLangIdx = Mathf.Clamp(m_IgnoredLangIdx, 0, LocalizationDialogue.LanguageFiles.Count - 1);
							m_Target.m_IgnoredLangs[i] = LocalizationDialogue.GetLanguage(m_IgnoredLangIdx);
						}
						if (GUILayout.Button(">"))
						{
							m_IgnoredLangIdx++;
							m_IgnoredLangIdx = Mathf.Clamp(m_IgnoredLangIdx, 0, LocalizationDialogue.LanguageFiles.Count - 1);
							m_Target.m_IgnoredLangs[i] = LocalizationDialogue.GetLanguage(m_IgnoredLangIdx);
						}
						if (GUILayout.Button("Remove"))
						{
							m_Target.m_IgnoredLangs.RemoveAt(i);
							i--;
						}
						GUILayout.EndHorizontal();
					}
				}
				
				if (GUILayout.Button("Test Next Lang"))
	            {
	                int index = 0;
	                foreach (var lang in LocalizationDialogue.LanguageFiles)
	                {
	                    if (lang.Key == LocalizationDialogue.CurrentLanguage)
	                        break;
	                    index++;
	                }
	
	                index = (index + 1) % LocalizationDialogue.LanguageFiles.Count;
	
	                int index2 = 0;
	                foreach (var lang in LocalizationDialogue.LanguageFiles)
	                {
	                    if (index2 == index)
	                    {
	                        LocalizationDialogue.CurrentLanguage = lang.Key;
	                        m_Target.Refresh();
	                        break;
	                    }
	                    index2++;
	                }
	            }
	
	            if (string.IsNullOrEmpty(m_Search))
	                return;
	
	            int count = 0;
	            string[] searchs = m_Search.Split(' ');
	            for (int i = 0; i < LocalizationDialogue.idString.Length; i++)
	            {
	                if (count >= m_MaxResults)
	                {
	                    if (GUILayout.Button("..."))
		                    m_MaxResults += 5;
						break;
	                }
	                bool contain = false;
	                string idString = LocalizationDialogue.idString[i];
	                for (int j = 0; j < searchs.Length; j++)
	                {
	                    if (idString.ToLower().Contains(searchs[j].ToLower()))
	                    {
	                        contain = true;
	                        break;
	                    }
	                }
	                if (contain)
	                {
	                    string additional = "";
	                    if (m_ShowText)
	                        additional = LocalizationDialogue.Get(idString).ToString();
	                    GUI.backgroundColor = Color.yellow;
	                    var style = new GUIStyle("Button");
	                    string buttonName = ($"{idString} / {additional}");
						if (buttonName.Length > 50)
							buttonName = buttonName.Substring(0, 50);
	                    if (GUILayout.Button(buttonName, style))
	                    {
	                        m_Target.m_LocalizedIDString = idString;
	                        m_Target.m_LocalizedID = -1;
	                        m_Target.m_LocalizedEnumId = LocalizationDialogue.ID.NONE;
	                        m_Target.Init();
	                        m_Target.Refresh();
	                    }
	                    GUI.backgroundColor = Color.white;
	                    count++;
	                }
	            }
	        }
	    }
	#endif
	}
}