namespace SheetXExample
{
	/***
	 * This script is automatically generated by SheetX.
	 ***/
	
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using UnityEngine;
	
	public abstract class LocalizationsManager
	{
	    public static Action OnLanguageChanged;
	
		public static readonly List<string> languages = new List<string>() { "english", "russian", };
		public static readonly string DefaultLanguage = "english";
		
	    public static string CurrentLanguage
	    {
	        get => PlayerPrefs.GetString("CurrentLanguage", DefaultLanguage);
	        set
	        {
	            if (CurrentLanguage != value && languages.Contains(value))
	            {
	                PlayerPrefs.SetString("CurrentLanguage", value);
	                Init("");
	            }
	        }
	    }
	
	    public static void Init(string pLang)
	    {
			if (languages.Contains(pLang))
				PlayerPrefs.SetString("CurrentLanguage", pLang);
			LocalizationUI.Init();
	        OnLanguageChanged?.Invoke();
	    }
	
	    public static IEnumerator InitAsync(string pLang)
	    {
			if (languages.Contains(pLang))
				PlayerPrefs.SetString("CurrentLanguage", pLang);
			yield return LocalizationUI.InitAsync();
	        OnLanguageChanged?.Invoke();
	    }
		
		public static void SetFolder(string pFolder)
		{
			LocalizationUI.Folder = pFolder;
		}
	
	    public static void UseAddressable(bool pValue)
	    {
			LocalizationUI.Addressable = pValue;
	    }
	
	    public static string GetSystemLanguage()
		{
			if (PlayerPrefs.HasKey("CurrentLanguage"))
				return PlayerPrefs.GetString("CurrentLanguage");
	
			var curLang = Application.systemLanguage;
			return curLang switch
			{
				SystemLanguage.English => "english",
				SystemLanguage.Russian => "russian",
				_ => "english",
	
			};
		}
	}
}